version: '2'
services:
    ecommerce-app:
        image: ecommerce
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://ecommerce-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=ecommerce
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ecommerce-mongodb:
        extends:
            file: mongodb.yml
            service: ecommerce-mongodb
